

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Phoenix(props) {
  const { nodes, materials } = useGLTF('/models/phoenix.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes['Material_001-material'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_1'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_2'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_3'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_4'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_5'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_6'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_7'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_8'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_9'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_10'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_11'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_12'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_13'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_14'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_15'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_16'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_17'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_18'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_19'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_20'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_21'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_22'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_23'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_24'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_25'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_26'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_27'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_28'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_29'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_30'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_31'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_32'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_33'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_34'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_35'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_36'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_37'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_38'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_39'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_40'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_41'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_42'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_43'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_44'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_45'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_46'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_47'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_48'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_49'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_50'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_51'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_52'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_53'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_54'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_55'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_56'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_57'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_58'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_59'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_60'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_61'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_62'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_63'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_64'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_65'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_66'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_67'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_68'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_69'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_70'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_71'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_72'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_73'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_74'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_75'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_76'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_77'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_78'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_79'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_80'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_81'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_82'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_83'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_84'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_85'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_86'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_87'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_88'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_89'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_90'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_91'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_92'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_93'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_94'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_95'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_96'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_97'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_98'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_99'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_100'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_101'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_102'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_103'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_104'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_105'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_106'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_107'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_108'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_109'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_110'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_111'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_112'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_113'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_114'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_115'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_116'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_117'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_118'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_119'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_120'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_121'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_122'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_123'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_124'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_125'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_126'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_127'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_128'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_129'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_130'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_131'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_132'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_133'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_134'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_135'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_136'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_137'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_138'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_139'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_140'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_141'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_142'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_143'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_144'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_145'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_146'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_147'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_148'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_149'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_150'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_151'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_152'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_153'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_154'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_155'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_156'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_157'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_158'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_159'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_160'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_161'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_162'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_163'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_164'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_165'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_166'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_167'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_168'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_169'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_170'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_171'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_172'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_173'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_174'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_175'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_176'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_177'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_178'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_179'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_180'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_181'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_182'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_183'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_184'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_185'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_186'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_187'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_188'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_189'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_190'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_191'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_192'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_193'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_194'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_195'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_196'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_197'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_198'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_199'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_200'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_201'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_202'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_203'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_204'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_205'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_206'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_207'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_208'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_209'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_210'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_211'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_212'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_213'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_214'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_215'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_216'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_217'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_218'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_219'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_220'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_221'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_222'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_223'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_224'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_225'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_226'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_227'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_228'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_229'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_230'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_231'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_232'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_233'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_234'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_235'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_236'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_237'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_238'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_239'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_240'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_241'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_242'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_243'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_244'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_245'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_246'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_247'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_248'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_249'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_250'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_251'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_252'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_253'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_254'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_255'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_256'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_257'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_258'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_259'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_260'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_261'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_262'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_263'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_264'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_265'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_266'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_267'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_268'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_269'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_270'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_271'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_272'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_273'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_274'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_275'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_276'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_277'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_278'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_279'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_280'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_281'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_282'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_283'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_284'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_285'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_286'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_287'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_288'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_289'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_290'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_291'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_292'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_293'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_294'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_295'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_296'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_297'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_298'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_299'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_300'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_301'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_302'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_303'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_304'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_305'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_306'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_307'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_308'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_309'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_310'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_311'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_312'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_313'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_314'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_315'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_316'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_317'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_318'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_319'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_320'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_321'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_322'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_323'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_324'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_325'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_326'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_327'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_328'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_329'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_330'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_331'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_332'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_333'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_334'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_335'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_336'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_337'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_338'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_339'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_340'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_341'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_342'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_343'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_344'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_345'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_346'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_347'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_348'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_349'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_350'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_351'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_352'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_353'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_354'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_355'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_356'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_357'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_358'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_359'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_360'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_361'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_362'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_363'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_364'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_365'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_366'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_367'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_368'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_369'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_370'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_371'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_372'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_373'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_374'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_375'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_376'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_377'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_378'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_379'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_380'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_381'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_382'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_383'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_384'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_385'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_386'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_387'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_388'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_389'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_390'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_391'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_392'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_393'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_394'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_395'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_396'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_397'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_398'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_399'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_400'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_401'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_402'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_403'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_404'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_405'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_406'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_407'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_408'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_409'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_410'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_411'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_412'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_413'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_414'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_415'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_416'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_417'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_418'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_419'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_420'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_421'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_422'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_423'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_424'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_425'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_426'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_427'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_428'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_429'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_430'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_431'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_432'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_433'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_434'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_435'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_436'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_437'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_438'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_439'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_440'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_441'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_442'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_443'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_444'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_445'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_446'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_447'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_448'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_449'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_450'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_451'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_452'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_453'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_454'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_455'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_456'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_457'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_458'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_459'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_460'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_461'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_462'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_463'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_464'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_465'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_466'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_467'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_468'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_469'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_470'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_471'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_472'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_473'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_474'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_475'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_476'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_477'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_478'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_479'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_480'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_481'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_482'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_483'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_484'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_485'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_486'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_487'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_488'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_489'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_490'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_491'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_492'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_493'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_494'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_495'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_496'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_497'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_498'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_499'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_500'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_501'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_502'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_503'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_504'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_505'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_506'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_507'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_508'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_509'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_510'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_511'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_512'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_513'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_514'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_515'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_516'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_517'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_518'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_519'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_520'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_521'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_522'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_523'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_524'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_525'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_526'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_527'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_528'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_529'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_530'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_531'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_532'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_533'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_534'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_535'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_536'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_537'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_538'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_539'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_540'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_541'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_542'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_543'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_544'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_545'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_546'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_547'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_548'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_549'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_550'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_551'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_552'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_553'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_554'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_555'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_556'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_557'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_558'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_559'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_560'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_561'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_562'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_563'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_564'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_565'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_566'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_567'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_568'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_569'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_570'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_571'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_572'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_573'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_574'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_575'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_576'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_577'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_578'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_579'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_580'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_581'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_582'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_583'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_584'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_585'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_586'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_587'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_588'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_589'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_590'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_591'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_592'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_593'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_594'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_595'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_596'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_597'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_598'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_599'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_600'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_601'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_602'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_603'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_604'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_605'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_606'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_607'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_608'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_609'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_610'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_611'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_612'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_613'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_614'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_615'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_616'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_617'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_618'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_619'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_620'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_621'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_622'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_623'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_624'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_625'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_626'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_627'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_628'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_629'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_630'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_631'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_632'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_633'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_634'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_635'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_636'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_637'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_638'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_639'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_640'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_641'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_642'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_643'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_644'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_645'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_646'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_647'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_648'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_649'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_650'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_651'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_652'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_653'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_654'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_655'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_656'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_657'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_658'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_659'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_660'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_661'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_662'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_663'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_664'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_665'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_666'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_667'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_668'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_669'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_670'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_671'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_672'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_673'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_674'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_675'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_676'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_677'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_678'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_679'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_680'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_681'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_682'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_683'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_684'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_685'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_686'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_687'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_688'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_689'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_690'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_691'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_692'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_693'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_694'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_695'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_696'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_697'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_698'].geometry} material={materials.Material_001} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Material_001-material_699'].geometry} material={materials.Material_001} position={[0.953, -0.189, -0.702]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/phoenix.glb')
